import { AiOutlineDashboard, AiFillSetting, AiOutlineUsergroupAdd } from 'react-icons/ai';
import { BiUser, BiCategory, BiAddToQueue, BiError } from 'react-icons/bi';
import {
  BsWatch,
  BsFileFontFill,
  BsUpload,
  BsDashSquare,
  BsCheck2Square,
  BsXSquare,
  BsThreeDots,
} from 'react-icons/bs';
import {
  FaUser,
  FaPhone,
  FaKey,
  FaEdit,
  FaChevronDown,
  FaSave,
  FaCloudUploadAlt,
  FaMoneyBillWave,
  FaPercent,
  FaLink,
  FaFacebookSquare,
  FaTwitterSquare,
  FaPhotoVideo,
} from 'react-icons/fa';
import { FcGoogle } from 'react-icons/fc';
import { FiRefreshCw, FiTrash2 } from 'react-icons/fi';
import { GiRomanToga } from 'react-icons/gi';
import { GoWatch } from 'react-icons/go';
import { GrUnlock, GrLock } from 'react-icons/gr';

import {
  IconCheck,
  IconX,
  IconSettings,
  IconSearch,
  IconPhoto,
  IconMessageCircle,
  IconTrash,
  IconArrowsLeftRight,
  IconUpload,
  IconAlertCircle,
  IconCheckbox,
  IconDotsVertical,
  IconGripVertical,
} from '@tabler/icons';
import {
  ImLocation2,
  ImCross,
  ImCheckmark,
  ImSearch,
  ImEye,
  ImEyeBlocked,
  ImCancelCircle,
  ImBlocked,
  ImFilter,
  ImManWoman,
  ImFolderUpload,
} from 'react-icons/im';
import { IoMdArrowRoundBack } from 'react-icons/io';
import {
  MdClose,
  MdEmail,
  MdLibraryAdd,
  MdDeleteForever,
  MdOutlineVideoLibrary,
  MdPayment,
  MdMenuBook,
  MdShopTwo,
  MdOutlineVideoCameraFront,
} from 'react-icons/md';
import {
  RiDeleteBin2Fill,
  RiDraftLine,
  RiFileEditFill,
  RiSortAsc,
  RiVideoUploadFill,
} from 'react-icons/ri';
import { SiAddthis } from 'react-icons/si';

export {
  AiOutlineDashboard,
  AiFillSetting,
  AiOutlineUsergroupAdd,
  BiUser,
  BiCategory,
  BiAddToQueue,
  BiError,
  BsWatch,
  BsFileFontFill,
  BsUpload,
  BsDashSquare,
  BsCheck2Square,
  BsXSquare,
  BsThreeDots,
  FaUser,
  FaPhone,
  FaKey,
  FaEdit,
  FaSave,
  FaChevronDown,
  FaCloudUploadAlt,
  FaMoneyBillWave,
  FaPercent,
  FaLink,
  FaFacebookSquare,
  FaTwitterSquare,
  FaPhotoVideo,
  FcGoogle,
  FiRefreshCw,
  FiTrash2,
  GiRomanToga,
  GoWatch,
  GrUnlock,
  GrLock,
  IconCheck,
  IconSettings,
  IconSearch,
  IconPhoto,
  IconMessageCircle,
  IconTrash,
  IconArrowsLeftRight,
  IconUpload,
  IconX,
  IconAlertCircle,
  IconCheckbox,
  IconDotsVertical,
  IconGripVertical,
  ImSearch,
  ImLocation2,
  ImCross,
  ImCheckmark,
  ImManWoman,
  ImEye,
  ImEyeBlocked,
  ImCancelCircle,
  ImBlocked,
  ImFilter,
  ImFolderUpload,
  IoMdArrowRoundBack,
  MdClose,
  MdEmail,
  MdLibraryAdd,
  MdDeleteForever,
  MdOutlineVideoLibrary,
  MdPayment,
  MdMenuBook,
  MdShopTwo,
  MdOutlineVideoCameraFront,
  RiDeleteBin2Fill,
  RiDraftLine,
  RiFileEditFill,
  RiSortAsc,
  RiVideoUploadFill,
  SiAddthis,
};
